### ISSUE TITLE
dub package and pdf/svg support

### ISSUE THREAD

**Issue by BlackEdder** [cairoD/cairoD#29]
Is there a way to use the dub package with pdf/svg support enabled?

If not, would a pull request where they are enabled by default be welcomed? Or can we use dub subPackages to define cairod:pdf etc (would need the source code to be reorganized)?

**Comment by jpf91** [comment]
I think enabling PDF and SVG by default is fine. Those should be supported by most cairo binaries AFAICS.


Having subpackages would be a nice solution. The `createFromNative` function in `cairo.cairo` currently needs to statically know all cairo feature flags though. It would be possible to change this to a runtime check (for example, keep a hashtable of `delegate Surface(cairo_surface_t*)[cairo_surface_type_t]` where addon packages register themselves via module constructors.)

However, this introduces many corner-cases: You need to synchronize access to this hashtable as addons could get registered in different threads. Also: what happens if:

* The PDF addon is not used by library A
* library A calls createFromNative on a pdf surface, gets a `Surface`
* library B is dynamically loaded. It also loads the PDF addon
* similar calls from library A will now create `PDFSurface`s

I'm not sure if this really is a problem, but it introduces some corner cases which would need to be carefully thought through.


Back when cairoD was developed, dub was not as famous. The idea was to autodetect the features the installed cairo C library offers (by compiling C test scripts which check for `CAIRO_HAS_FT_FONT` and similar defines (often done with autoconf)). This would then always produce a cairoD library which matches the features of the installed cairo library. Unfortunately Dub does not support this. And AFAIK it does not even support extended manual package configuration (such as using multiple configurations at the same time). It might make sense to ask for advice in the dub forum.

**Comment by BlackEdder** [comment]
You can add a script to dub. I guess the script could check for available features and enable/disable them on the fly.

I guess the c header/configuration files aren't accessible from D?

**Comment by jpf91** [comment]
Thanks for that information :-) I didn't know there's a `preBuildCommands` configuration option. It seems hard to make 100% portable build scripts that way (should work with all D compilers and automatically select the available one) but I hope it's good enough: Updated documentation:
https://github.com/cairoD/cairoD

Untested on windows for now and probably needs some more testing anyway. Once the next DMD release is finished we'll have full winapi support in druntime. The windows code should be updated to the new buildings and then all dependencies are available via dub or in phobos/druntime.

**Comment by BlackEdder** [comment]
Thanks! That was fast. The script works wonderfully here.
